import type { Island } from "./islands-api";

export const FALLBACK_ISLANDS: Island[] = [
  {
    id: 1,
    name: "Amami Oshima",
    name_jp: "奄美大島",
    prefecture: "Kagoshima",
    description: "UNESCO World Natural Heritage site with endemic species and subtropical forests.",
    long_description:
      "Amami Oshima is the largest island in the Amami archipelago and was designated a UNESCO World Natural Heritage Site in 2021. Home to the critically endangered Amami rabbit, the island represents one of Japan's most biodiverse regions. Hundreds of traditional kominka homes sit abandoned as the population ages.",
    population: 55000,
    area_km2: 712.4,
    latitude: 28.3,
    longitude: 129.5,
    conservation_priority: "critical",
    status: "depopulating",
    image_url: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800",
    gallery_urls: "",
    akiya_count: 340,
    volunteer_needed: true,
    volunteer_count: 12,
    featured: true,
    tags: "UNESCO,endemic species,kominka,silk weaving",
    peak_season: "March-May, October-November",
    access_info: "Ferry from Kagoshima (11h) or flight from Kagoshima/Osaka",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 2,
    name: "Naoshima",
    name_jp: "直島",
    prefecture: "Kagawa",
    description: "The art island of the Seto Inland Sea, revived through contemporary art.",
    long_description:
      "Once a declining industrial island, Naoshima was transformed by Benesse Corporation and architect Tadao Ando into a living museum. The Chichu Art Museum and Art House Project have turned former residents' homes into immersive artworks.",
    population: 3000,
    area_km2: 8.1,
    latitude: 34.46,
    longitude: 133.99,
    conservation_priority: "medium",
    status: "reviving",
    image_url: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800",
    gallery_urls: "",
    akiya_count: 45,
    volunteer_needed: false,
    volunteer_count: 0,
    featured: true,
    tags: "art island,Tadao Ando,Benesse,Seto Inland Sea",
    peak_season: "April-June, September-November",
    access_info: "Ferry from Uno Port, Okayama (20 min)",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 3,
    name: "Teshima",
    name_jp: "豊島",
    prefecture: "Kagawa",
    description: "Organic farming revival and world-class art on a once-polluted island.",
    long_description:
      "Teshima was used as an illegal industrial waste dump in the 1970s-1990s. Through decades of cleanup, it has emerged as a symbol of resilience with the Teshima Art Museum and organic farms.",
    population: 800,
    area_km2: 14.5,
    latitude: 34.49,
    longitude: 134.18,
    conservation_priority: "high",
    status: "reviving",
    image_url: "https://images.unsplash.com/photo-1578637387939-43c525550085?w=800",
    gallery_urls: "",
    akiya_count: 120,
    volunteer_needed: true,
    volunteer_count: 8,
    featured: false,
    tags: "art island,organic farming,Seto Inland Sea",
    peak_season: "April-June, September-November",
    access_info: "Ferry from Uno Port (35 min)",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 4,
    name: "Inujima",
    name_jp: "犬島",
    prefecture: "Okayama",
    description: "A tiny island with 50 residents and a copper refinery turned art gallery.",
    long_description:
      "Inujima has only 50 elderly residents. A copper smelting refinery left distinctive brick ruins now incorporated into the Inujima Seirensho Art Museum. Without intervention, the island faces complete abandonment.",
    population: 50,
    area_km2: 0.54,
    latitude: 34.55,
    longitude: 134.18,
    conservation_priority: "critical",
    status: "depopulating",
    image_url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800",
    gallery_urls: "",
    akiya_count: 28,
    volunteer_needed: true,
    volunteer_count: 3,
    featured: false,
    tags: "Art House Project,micro-island,urgent",
    peak_season: "March-November",
    access_info: "Ferry from Hoden Port, Okayama (10 min)",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 5,
    name: "Hashima",
    name_jp: "端島",
    prefecture: "Nagasaki",
    description: "Gunkanjima — Battleship Island — the world's most haunting abandoned cityscape.",
    long_description:
      "Once Japan's most densely populated place, Hashima was abandoned in 84 days when Mitsubishi's coal mines closed in 1974. The crumbling concrete apartments and cinema stand frozen in time as a UNESCO World Heritage Site.",
    population: 0,
    area_km2: 0.063,
    latitude: 32.63,
    longitude: 129.74,
    conservation_priority: "high",
    status: "abandoned",
    image_url: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800",
    gallery_urls: "",
    akiya_count: 0,
    volunteer_needed: false,
    volunteer_count: 0,
    featured: true,
    tags: "Gunkanjima,UNESCO,coal mining,dark tourism",
    peak_season: "Year-round",
    access_info: "Boat tour from Nagasaki Port (45 min)",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 6,
    name: "Aoshima",
    name_jp: "青島",
    prefecture: "Ehime",
    description: "The Cat Island — 13 human residents, 160 cats, and zero cars.",
    long_description:
      "Aoshima went viral in 2015 when a resident's plea for cat food donations revealed: 160 cats and only 13 elderly residents. Once a fishing community of 900, the island now has no shops, no medical facilities, no vending machines.",
    population: 13,
    area_km2: 0.49,
    latitude: 33.7,
    longitude: 132.55,
    conservation_priority: "critical",
    status: "depopulating",
    image_url: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800",
    gallery_urls: "",
    akiya_count: 22,
    volunteer_needed: true,
    volunteer_count: 2,
    featured: false,
    tags: "cat island,micro-island,urgent,fishing heritage",
    peak_season: "Spring and autumn",
    access_info: "Ferry from Nagahama Port, Ehime (30 min) — one ferry per day",
    created_at: new Date().toISOString(),
    updated_at: null,
  },
];

export const FEATURED_ISLAND = FALLBACK_ISLANDS[0];
